# Generated by Django 3.0.5 on 2020-05-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='integredients',
            new_name='intgredients',
        ),
    ]
