# Generated by Django 3.0.5 on 2020-05-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intgredient',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='intgredients',
            new_name='ingredients',
        ),
    ]
