name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  WEB_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/web

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo ::set-env name=WEB_IMAGE::${{ env.WEB_IMAGE }}        

    # Runs a single command using the runners shell
    - name: run test and linting
      run: docker-compose -f docker-compose.ci.yml run --rm web sh -c "python manage.py test && flake8"

    - name: Log in to GitHub Packages
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Pull images
      run: |
        docker pull ${{ env.WEB_IMAGE }} || true

    - name: Build images
      run: |
        docker-compose -f docker-compose.ci.yml build

    - name: Push images
      run: |
        docker push ${{ env.WEB_IMAGE }}
